#!/usr/bin/env ruby

require "foobara/load_dotenv"
Foobara::LoadDotenv.run!(dir: __dir__)

require "foobara/llm_backed_command"
require "foobara/sh_cli_connector"

class ComputeExponent < Foobara::LlmBackedCommand
  inputs base: :integer, exponent: :integer
  result :integer
end

Foobara::CommandConnectors::ShCliConnector.new(single_command_mode: ComputeExponent).run(ARGV)
