source "https://rubygems.org"

# plugin 'bundler-graph'
# gem "foobara-http-command-connector", path: "../../../http-command-connector"
# gem "foobara", "~> 0.0.92", path: "../../../foobara"
# gem "foobara-http-api-command", path: "../../../http-api-command"

gem "foobara-anthropic-api", "< 2.0.0"
gem "foobara-dotenv-loader", "< 2.0.0"
gem "foobara-llm-backed-command", path: "../.."
gem "foobara-local-files-crud-driver", "< 2.0.0"
gem "foobara-ollama-api", "< 2.0.0"
gem "foobara-open-ai-api", "< 2.0.0"
gem "foobara-rack-connector", "< 2.0.0"
gem "foobara-remote-imports", "< 2.0.0" # , path: "../../../remote-imports"
gem "foobara-sh-cli-connector", "< 2.0.0"
gem "puma"
gem "rackup"

gem "irb"
gem "pry"
gem "pry-byebug"
# Eliminates warning due to above not requiring it
gem "ostruct"
