source "https://rubygems.org"

# plugin 'bundler-graph'
# gem "foobara-ai", path: "../../../ai"
# gem "foobara-http-api-command", path: "../../../http-api-command"
# gem "foobara-http-command-connector", path: "../../../http-command-connector"
# gem "foobara-json-schema-generator", path: "../../../json-schema-generator"

gem "foobara", ">= 0.1.1", "< 2.0.0" # , path: "../../../foobara"
gem "foobara-anthropic-api", "< 2.0.0" # , path: "../../../anthropic-api"
gem "foobara-dotenv-loader", "< 2.0.0"
gem "foobara-llm-backed-command" # , path: "../.."
gem "foobara-local-files-crud-driver", "< 2.0.0" # , path: "../../../local-files-crud-driver"
gem "foobara-ollama-api", "< 2.0.0" # , path: "../../../ollama-api"
gem "foobara-open-ai-api", "< 2.0.0" # , path: "../../../open-ai-api"
gem "foobara-rack-connector", "< 2.0.0" # , path: "../../../rack-connector"
gem "foobara-remote-imports", "< 2.0.0" # , path: "../../../remote-imports"
gem "foobara-sh-cli-connector", "< 2.0.0" # , path: "../../../sh-cli-connector"
gem "puma"
gem "rackup"

gem "irb"
gem "pry"
gem "pry-byebug"
# Eliminates warning due to above not requiring it
gem "ostruct"
