#!/usr/bin/env ruby

# ENV["ANTHROPIC_API_KEY"] = "<your key here>"

# if using .env like this instead of setting ENV then run `gem install foobara-dotenv-loader`
require "foobara/load_dotenv"
Foobara::LoadDotenv.run!(dir: __dir__)

require "foobara/llm_backed_command"

class DetermineLanguage < Foobara::LlmBackedCommand
  inputs code_snippet: :string
  result most_likely: :string, probabilities: { ruby: :float, c: :float, smalltalk: :float, java: :float }
end

puts DetermineLanguage.run!(code_snippet: "puts 'Hello, World'")
