#!/usr/bin/env ruby

require "foobara/load_dotenv"
Foobara::LoadDotenv.run!(dir: __dir__)

require "foobara/anthropic_api"
require "foobara/open_ai_api"
require "foobara/ollama_api"

require "foobara/llm_backed_command"
require "foobara/sh_cli_connector"

module Math
  class ComputeExponent < Foobara::LlmBackedCommand
    description "Takes an integer base and exponent and returns the base raised to the exponent"

    inputs do
      base :integer, :required
      exponent :integer, :required
      llm_model Foobara::Ai::AnswerBot::Types.model_enum, default: "claude-3-7-sonnet-20250219"
    end

    result :integer
  end
end

Foobara::CommandConnectors::ShCliConnector.new(
  single_command_mode: Math::ComputeExponent
).run(ARGV)
